# Generated by Django 3.0.7 on 2020-10-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('imdb_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('dob', models.DateField(blank=True, null=True)),
                ('headshot', models.URLField(blank=True, null=True)),
                ('career_gross', models.IntegerField(blank=True, null=True)),
                ('average_box_office_return', models.IntegerField(blank=True, null=True)),
                ('career_screen_average', models.IntegerField(blank=True, null=True)),
                ('weeks_at_uk_cinemas', models.IntegerField(blank=True, null=True)),
                ('num_of_films', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('imdb_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('dob', models.DateField(blank=True, null=True)),
                ('headshot', models.URLField(blank=True, null=True)),
                ('career_gross', models.IntegerField(blank=True, null=True)),
                ('average_box_office_return', models.IntegerField(blank=True, null=True)),
                ('career_screen_average', models.IntegerField(blank=True, null=True)),
                ('weeks_at_uk_cinemas', models.IntegerField(blank=True, null=True)),
                ('num_of_films', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('imdb_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('dob', models.DateField(blank=True, null=True)),
                ('headshot', models.URLField(blank=True, null=True)),
                ('career_gross', models.IntegerField(blank=True, null=True)),
                ('average_box_office_return', models.IntegerField(blank=True, null=True)),
                ('career_screen_average', models.IntegerField(blank=True, null=True)),
                ('weeks_at_uk_cinemas', models.IntegerField(blank=True, null=True)),
                ('num_of_films', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=60)),
                ('gross', models.IntegerField(blank=True, null=True)),
                ('opening', models.IntegerField(blank=True, null=True)),
                ('screen_average', models.IntegerField(blank=True, null=True)),
                ('run_length', models.IntegerField(blank=True, null=True)),
                ('best_rank', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('run_time', models.IntegerField(blank=True, null=True)),
                ('poster', models.URLField(blank=True, null=True)),
                ('rt', models.IntegerField(blank=True, null=True)),
                ('actors', models.ManyToManyField(blank=True, related_name='film_actors', to='front_end.Actor')),
                ('director', models.ManyToManyField(blank=True, related_name='film_directors', to='front_end.Director')),
                ('writers', models.ManyToManyField(blank=True, related_name='film_writers', to='front_end.Writer')),
            ],
        ),
    ]
