# Generated by Django 3.0.7 on 2020-10-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('imdb_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('dob', models.DateField(blank=True, null=True)),
                ('headshot', models.URLField(blank=True, null=True)),
                ('career_gross', models.IntegerField(blank=True, null=True)),
                ('average_box_office_return', models.IntegerField(blank=True, null=True)),
                ('career_screen_average', models.IntegerField(blank=True, null=True)),
                ('weeks_at_uk_cinemas', models.IntegerField(blank=True, null=True)),
                ('num_of_films', models.IntegerField(blank=True, null=True)),
                ('talent_type', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='talent',
            field=models.ManyToManyField(blank=True, related_name='film_talent', to='front_end.Talent'),
        ),
    ]
