# Generated by Django 3.0.7 on 2020-10-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0002_auto_20201013_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='imdb_id',
            field=models.CharField(max_length=20),
        ),
    ]
