# Generated by Django 3.0.7 on 2020-10-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0003_auto_20201013_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='imdb_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='imdb_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
