# Generated by Django 3.0.7 on 2020-10-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0004_auto_20201013_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmTalent',
            fields=[
                ('imdb_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('dob', models.DateField(blank=True, null=True)),
                ('headshot', models.URLField(blank=True, null=True)),
                ('career_gross', models.IntegerField(blank=True, null=True)),
                ('average_box_office_return', models.IntegerField(blank=True, null=True)),
                ('career_screen_average', models.IntegerField(blank=True, null=True)),
                ('weeks_at_uk_cinemas', models.IntegerField(blank=True, null=True)),
                ('num_of_films', models.IntegerField(blank=True, null=True)),
                ('talent_type', models.IntegerField()),
            ],
        ),
    ]
