# Generated by Django 3.0.7 on 2020-10-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0006_auto_20201014_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilmTalent',
        ),
        migrations.RemoveField(
            model_name='film',
            name='talent',
        ),
        migrations.DeleteModel(
            name='Talent',
        ),
    ]
