# Generated by Django 3.0.7 on 2020-10-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0007_auto_20201014_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='talent_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='talent_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='talent_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
