# Generated by Django 3.0.7 on 2020-10-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0008_auto_20201015_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='gross_2002',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gross_2003',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gross_2004',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gross_2005',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gross_2006',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gross_2007',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gross_2008',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gross_2009',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gross_2010',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gross_2011',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gross_2012',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gross_2013',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gross_2014',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gross_2015',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gross_2016',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gross_2017',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gross_2018',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gross_2019',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gross_2020',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='gross_2002',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='gross_2003',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='gross_2004',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='gross_2005',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='gross_2006',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='gross_2007',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='gross_2008',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='gross_2009',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='gross_2010',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='gross_2011',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='gross_2012',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='gross_2013',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='gross_2014',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='gross_2015',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='gross_2016',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='gross_2017',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='gross_2018',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='gross_2019',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='gross_2020',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='gross_2002',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='gross_2003',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='gross_2004',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='gross_2005',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='gross_2006',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='gross_2007',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='gross_2008',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='gross_2009',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='gross_2010',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='gross_2011',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='gross_2012',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='gross_2013',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='gross_2014',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='gross_2015',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='gross_2016',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='gross_2017',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='gross_2018',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='gross_2019',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='gross_2020',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
